### ISSUE TITLE
Will it work for REST API style?

### ISSUE THREAD

**Issue by chika-kasymov** [stormpath/Turnstile-Vapor-Example#1]
For example, I have iOS client and did login with Facebook SDK. I get access token and some other stuff, how can I use your library to login using these data?

**Comment by edjiang** [comment]
Yep! You'd use the `AccessToken` credentials type to authenticate, and validate it in your user object. It's not quite demonstrated in this project, but you'd basically use it in a similar way to how `APIKey` is used in this project.

**Comment by chika-kasymov** [comment]
OK, thanks for reply!
