### ISSUE TITLE
Sesssion

### ISSUE THREAD

**Issue by pjcook** [stormpath/Turnstile-Vapor-Example#2]
In the Credentials class there is a struct called Sesssion
I assume this is a typo and should be Session, or would that conflict with the Vapor Session class?

**Comment by edjiang** [comment]
Yes, that's a typo in Turnstile, unfortunately. We'll get that fixed =]

https://github.com/stormpath/Turnstile/issues/25

**Comment by edjiang** [comment]
Fixed
